
development:
  adapter: postgresql
  encoding: unicode
  database: shop_db
  host: localhost
  pool: 5
  username: vlad
  password: secret
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: shop_db
  host: localhost
  pool: 5
  username: vlad
  password: secret
  timeout: 5000
