development:
  adapter: postgresql
  database: shop_db
  encoding: unicode
  host: localhost
  password: secret
  pool: 5
  timeout: 5000
  username: vlad

test:
  adapter: postgresql
  database: shop_db_test
  encoding: unicode
  host: localhost
  password: secret
  pool: 5
  timeout: 5000
  username: vlad
